/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeadershipProfile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const NewsEvent = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'imageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addLeadershipProfile' : IDL.Func([LeadershipProfile], [IDL.Nat], []),
  'addNewsEvent' : IDL.Func([NewsEvent], [IDL.Nat], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllLeadershipProfiles' : IDL.Func(
      [],
      [IDL.Vec(LeadershipProfile)],
      ['query'],
    ),
  'getAllNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
  'removeLeadershipProfile' : IDL.Func([IDL.Nat], [], []),
  'removeNewsEvent' : IDL.Func([IDL.Nat], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeadershipProfile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const NewsEvent = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'imageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addLeadershipProfile' : IDL.Func([LeadershipProfile], [IDL.Nat], []),
    'addNewsEvent' : IDL.Func([NewsEvent], [IDL.Nat], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllLeadershipProfiles' : IDL.Func(
        [],
        [IDL.Vec(LeadershipProfile)],
        ['query'],
      ),
    'getAllNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
    'removeLeadershipProfile' : IDL.Func([IDL.Nat], [], []),
    'removeNewsEvent' : IDL.Func([IDL.Nat], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };